# Generated by Django 4.1.7 on 2026-03-17 02:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Running', '달리기'), ('Swimming', '수영'), ('Cycling', '자전거'), ('Gym', '헬스장'), ('Yoga', '요가'), ('Walking', '산책'), ('Sports', '스포츠')], help_text='활동 종류', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='calories_burned',
            field=models.IntegerField(help_text='소모 칼로리', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='활동 날짜'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(help_text='지속시간 (분)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(help_text='순위', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='octofit_tracker.team'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='total_score',
            field=models.IntegerField(default=0, help_text='총 점수', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='업데이트 날짜'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 날짜'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(help_text='팀 설명'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='팀 멤버', related_name='teams', to='octofit_tracker.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='팀 이름', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 날짜'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='이메일 주소', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='사용자 이름', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='사용자 비밀번호', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 날짜'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(help_text='운동 프로그램 설명'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', '쉬움'), ('Medium', '중간'), ('Hard', '어려움')], help_text='난이도', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.JSONField(help_text='운동 목록 (JSON 형식)'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(help_text='운동 프로그램 이름', max_length=100),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-date'], name='activities_user_id_5cc191_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activities_activit_f14342_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['rank'], name='leaderboard_rank_4ad7a0_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['total_score'], name='leaderboard_total_s_1171f1_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='teams_name_12b53a_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['-created_at'], name='teams_created_40fe06_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='users_created_30b417_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['difficulty_level'], name='workouts_difficu_c628cf_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['-created_at'], name='workouts_created_337f35_idx'),
        ),
    ]
